<?php
// $Id$

/**
 * @file
 * Main file for the Save Draft module, which adds a 'Save as Draft' button to content types.
 */

/**
 * Implements hook_form_alter().
 */
 
function save_draft_form_alter(&$form, &$form_state, $form_id) {
  $form_id = strstr($form_id, '_');
  $form_id = substr($form_id, 1);
  if ($form_id == 'node_form') {
    $form['buttons']['draft'] = array(
      '#type' => 'submit',
      '#class' => 'form-submit',
      '#value' => t('Save as Draft'),
      '#weight' => '9',
      '#submit' => array('save_draft_submit')
    );
  }
}

/**
 * Handles save draft form submission
 */
function save_draft_submit($form, &$form_state) {
  $form_state['values']['status'] = 0;
  node_form_submit($form, $form_state);
}