<?php
// $Id$

/**
 * @file
 * Main file for the Save Draft module, which adds a 'Save as Draft' button to content types.
 */
 
 /**
  * Implements hook_perm().
  */
 
 function save_draft_perm() {
   return array('save draft');
 }

/**
 * Implements hook_form_alter().
 */
 
function save_draft_form_alter(&$form, &$form_state, $form_id) {
  $form_id = substr($form_id, -9);
  if ($form_id == 'node_form' && user_access('save draft')) {
    $form['options']['#title'] = t('Content promotion options');
    $form['options']['status'] = false;
    if (isset($form['nid']['#value'])) {
      if ($form['#node']->status == 1) {
        $form['actions']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Unpublish'),
          '#weight' => '9',
          '#submit' => array('save_draft_submit')
        );
        $form['actions']['submit']['#value'] = t('Save');
        $form['actions']['submit']['#submit'] = array('publish_submit');
      }
      else {
        $form['actions']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Save'),
          '#weight' => '0',
          '#submit' => array('save_draft_submit')
        );
        $form['actions']['submit']['#value'] = t('Publish');
        $form['actions']['submit']['#submit'] = array('publish_submit');
      }
    }
    else {
      $form['actions']['draft'] = array(
        '#type' => 'submit',
        '#class' => 'form-submit',
        '#value' => t('Save as Draft'),
        '#weight' => '9',
        '#submit' => array('save_draft_submit')
      );
      $form['actions']['submit']['#value'] = t('Publish');
      $form['actions']['submit']['#submit'] = array('publish_submit');
    }
  }
}

/**
 * Handles save draft form submission
 */
function save_draft_submit($form, &$form_state) {
  $form_state['values']['status'] = 0;
  node_form_submit($form, $form_state);
}

/**
 * Handles publish form submission
 */
function publish_submit($form, &$form_state) {
  $form_state['values']['status'] = 1;
  node_form_submit($form, $form_state);
}